version: "3.8"

services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=postgres
            - POSTGRES_DB=my_database
        networks:
            - app-network
        volumes:
            - db-data:/var/lib/postgresql/data

    backend:
        environment: 
            - POSTGRES_HOST=postgres
        container_name: backend
        depends_on: 
            - postgres
        build: 
            context: ./server
        ports:
            - 8080:8080
            - 8081:8081
        volumes: 
            - .:/app
        networks:
            - app-network

    frontend:
        container_name: frontend
        depends_on: 
            - backend
        build: 
            context: ./client
        ports:
            - 3000:3000
        networks:
            - app-network
        
networks:
    app-network:
        driver: bridge  
