version: "3"

services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=postgres
            - POSTGRES_DB=my_database
    backend:
        environment: 
            - POSTGRES_HOST=postgres
        container_name: backend
        depends_on: 
            - postgres
        build: 
            context: ./server
        ports:
            - 4000:4000
            - 4001:4001
        volumes: 
            - .:/app
            - /app/node_modules
    frontend:
        container_name: frontend
        depends_on: 
            - backend
        build: 
            context: ./client
        ports:
            - 3000:3000
        
            

  